call truffle.cmd test .\test\testautobuyer.js
call truffle.cmd test .\test\testcrossroad_DB_T.js
call truffle.cmd test .\test\testcrossroad_DB_T_Fill.js
call truffle.cmd test .\test\testcrossroad_DB_T_FillOver.js
call truffle.cmd test .\test\testcrossroad_DT_B_Callback.js
call truffle.cmd test .\test\testcrossroad_DT_B_CallbackOver.js
call truffle.cmd test .\test\testcrossroad_DT_B_Fill.js
call truffle.cmd test .\test\testcrossroad_DT_B_FillOver.js
call truffle.cmd test .\test\testcrossroad_DT_T.js
call truffle.cmd test .\test\testcrossroad_DT_T_Fill.js
call truffle.cmd test .\test\testcrossroad_DT_T_FillOver.js
call truffle.cmd test .\test\testcrossroad_records.js
call truffle.cmd test .\test\testcrossroad_WT_B_Callback.js
call truffle.cmd test .\test\testcrossroad_WT_B_CallbackOver.js
call truffle.cmd test .\test\testcrossroad_WT_B_Fill.js
call truffle.cmd test .\test\testcrossroad_WT_B_FillOver.js
call truffle.cmd test .\test\testcrossroad_WT_T.js
call truffle.cmd test .\test\testcrossroad_WT_T_Fill.js
call truffle.cmd test .\test\testcrossroad_WT_T_FillOver.js
